spring:
  
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: admin

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrapServers: localhost:9092
    productProducer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    productConsumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
